### ISSUE TITLE
Generalized token code

### ISSUE THREAD

**Issue by apmilen** [vulcanize/amp2rcoin#1]
I thought you might like to know about our reusable token contracts: [ds-token](https://github.com/nexusdev/ds-token) and [erc20](https://github.com/nexusdev/erc20), since they could save you some time.

Here is a [write up](http://blog.nexusdev.us/dapple-tutorial/) about how to create an upgradeable system with ds-token.

**Comment by AdamScislowicz** [comment]
thank you. I have switched to using the erc20. ds-token looks interesting but too much for the current schedule, will investigate migrating towards using that next time.
